### PR TITLE
Rename the default branch to main.

### PR DESCRIPTION
**Pull request by martijneken**

### CODE REVIEW

**Comment by martijneken** [comment]
Sent these PRs to fix existing CI breakages:
- https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/235 for reactor builds
- https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/236 for blaze CI check

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
Could you also fix links in the `README.md` file? Thanks!

**Comment by martijneken** [comment]
> Could you also fix links in the `README.md` file? Thanks!

Done, good catch. PTAL.

**Review by PiotrSikora — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
