### PR TITLE
Update libc (transitive dependency) to v0.2.90.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by mathetake — APPROVED** [review]
LGTM (I'm wondering if we could automate the transitive dependency update? e.g. adding scheduled github action to create PRs like this)

**Comment by PiotrSikora** [comment]
> LGTM (I'm wondering if we could automate the transitive dependency update? e.g. adding scheduled github action to create PRs like this)

We could... Alternatively, we could ignore transitive dependencies, since we need them only for Bazel builds (we don't ship `Cargo.lock`, so Cargo builds are always using the latest versions), and even then, most of them are used only in examples:
```
$ cargo tree --target=wasm32-wasi --edges normal
proxy-wasm v0.1.3 (/path/to/proxy-wasm-rust-sdk)
├── hashbrown v0.11.0
│   └── ahash v0.7.2
│       ├── getrandom v0.2.2
│       │   ├── cfg-if v1.0.0
│       │   └── wasi v0.10.2+wasi-snapshot-preview1
│       └── once_cell v1.7.2
└── log v0.4.14
    └── cfg-if v1.0.0
```

**Comment by PiotrSikora** [comment]
> > LGTM (I'm wondering if we could automate the transitive dependency update? e.g. adding scheduled github action to create PRs like this)
> 
> We could... Alternatively, we could ignore transitive dependencies, since we need them only for Bazel builds (we don't ship `Cargo.lock`, so Cargo builds are always using the latest versions), and even then, most of them are used only in examples:
> 
> ```
> $ cargo tree --target=wasm32-wasi --edges normal
> proxy-wasm v0.1.3 (/path/to/proxy-wasm-rust-sdk)
> ├── hashbrown v0.11.0
> │   └── ahash v0.7.2
> │       ├── getrandom v0.2.2
> │       │   ├── cfg-if v1.0.0
> │       │   └── wasi v0.10.2+wasi-snapshot-preview1
> │       └── once_cell v1.7.2
> └── log v0.4.14
>     └── cfg-if v1.0.0
> ```

@mathetake any thoughts on this?

**Comment by mathetake** [comment]
Sorry forgot to reply. If we could assume that majority of users would use cargo, not Basel, then let’s ignore the transitive dependencies upgrades.

**Comment by codefromthecrypt** [comment]
I agree. the bazel part is distracting and personally not helpful even if some like it.

**Comment by PiotrSikora** [comment]
@codefromthecrypt yup, the freshness check was removed in #99, and I'm going to update Bazel deps only before creating a new release.

**Pull request merged**
