### PR TITLE
Update ABI to Proxy-Wasm ABI v0.2.1.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by gbrail — APPROVED** [review]
LGTM -- it's great to be able to use the whole new ABI. Thanks.

**Comment by nullpo-head** [comment]
Hi @PiotrSikora , I am curious about the status of this PR. Do you have any idea when this PR will be merged, or is there some kind of blocker? 

By the way, I would also appreciate it if you could tell me if there is a written specification of ABI v0.2.0/1 apart from the implementation (https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/src/wasm.cc#L128-L140).

**Comment by PiotrSikora** [comment]
> Hi @PiotrSikora , I am curious about the status of this PR. Do you have any idea when this PR will be merged, or is there some kind of blocker?

There is no blocker, it should have been merged months ago, but I wanted to add one more change before breaking API, and it felt behind the schedule. It was quite silly in hindsight.

I'll try to make that change over the weekend, but even if it doesn't happen, I'll merge this PR on Monday.

Feel free to ping me here if it's not done by then.

> By the way, I would also appreciate it if you could tell me if there is a written specification of ABI v0.2.0/1 apart from the implementation (https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/src/wasm.cc#L128-L140).

Nope, sorry.

**Comment by nullpo-head** [comment]
> > Hi @PiotrSikora , I am curious about the status of this PR. Do you have any idea when this PR will be merged, or is there some kind of blocker?
> 
> There is no blocker, it should have been merged months ago, but I wanted to add one more change before breaking API, and it felt behind the schedule. It was quite silly in hindsight.
> 
> I'll try to make that change over the weekend, but even if it doesn't happen, I'll merge this PR on Monday.
> 
> Feel free to ping me here if it's not done by then.
> 
> > By the way, I would also appreciate it if you could tell me if there is a written specification of ABI v0.2.0/1 apart from the implementation (https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/src/wasm.cc#L128-L140).
> 
> Nope, sorry.

Thank you so much for your quick answer! It helps a lot!

**Comment by jcruger-godaddy** [comment]
@PiotrSikora just wanted to follow up here on the plans for merge. Appreciate the hard work on this

**Comment by jcrugzz** [comment]
@PiotrSikora hey wanted to check in if there are any blockers on this. Would be great to get a release out when you can.

**Comment by PiotrSikora** [comment]
@jcrugzz thanks for the nudge. I want to spin one more 0.1.x release before merging this, since it's a breaking change.

The new release was mostly blocked on the gRPC support (merged a few days ago), but there are a few small fixes that I want get in... It should be done by the end of this week, and I'll merge this afterwards.

**Comment by jcrugzz** [comment]
@PiotrSikora Thanks for the response, appreciate your work here

**Comment by jcrugzz** [comment]
@PiotrSikora hey just checking in here. I know how busy things can be so just seeing where we are at. All the best

**Review by mathetake — APPROVED** [review]

**Pull request merged**
