### PR TITLE
Add support for calling foreign functions.

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Created a new pr because of problems with rebase.
See https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/84 for all the history

Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>

Sorry @PiotrSikora for the mess.

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
not sure what to do here https://github.com/proxy-wasm/proxy-wasm-rust-sdk/runs/5846359105?check_suite_focus=true

**Comment by PiotrSikora** [comment]
> not sure what to do here https://github.com/proxy-wasm/proxy-wasm-rust-sdk/runs/5846359105?check_suite_focus=true

Ignore it, it's unrelated to this PR (see: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/issues/142).

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Comment by PiotrSikora** [comment]
> Sorry @PiotrSikora for the mess.

No worries, it's an issue with DCO and code review suggestions.

**Pull request merged**
