### PR TITLE
Update dependencies and resolve workflow failures

### PR DESCRIPTION
**Pull request by Swaagie**
Thought this might be a meaningful first contribution, updated dependencies and opted out of using the `chrono` crate for the `hello_world` example. I have no experience with bazel/raze before (up until now) so if I'm making crazy changes please let me know. 

- Updated `cargo-raze` to 0.14.1 (and adjusted build configs)
- Updated to use rust edition 2021 as `cargo metadata` depended on latest without having to use nightly.
- Removed `chrono` crate in favor of `time` crate to avoid having to wait [for a resolution for the sec vun](https://github.com/chronotope/chrono/pull/578#issuecomment-974493484)
- Updated `rust_rules` to [b3ddf6f096887b757ab1a661662a95d6b2699fa7](https://github.com/bazelbuild/rules_rust/commit/b3ddf6f096887b757ab1a661662a95d6b2699fa7)
- Fixed clippy suggested safe read of potentially unallocated memory with `MaybeUninit`
- Regenerated lockfiles

Happy to change and update the PR where needed.

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Thanks, this looks fine, but could you please split this into multiple self-contained PRs?

**Comment by mswaagman-godaddy** [comment]
Certainly, let the cherry picking commence 😄

**Comment by Swaagie** [comment]
Certainly, let the cherry picking commence 😄

**Comment by Swaagie** [comment]
Closing this in favor of smaller isolated PRs as requested

**Pull request closed without merging**
